### ISSUE TITLE
Couldn't create policy: 'source'

### ISSUE THREAD

**Issue by s4s0l** [containers/udica#33]
**Describe the bug**
Unable to generate policy.
```
# podman inspect 8e | udica -j -  my_container
Couldn't create policy: 'source'
```
**To Reproduce**
1. Fresh fedora 30 aws instance
2. Follow installation instructions in README.md

**Expected behavior**
Policy generated

**Comment by wrabcak** [comment]
Hi @s4s0l , 

Could you please attahc output of:
# rpm -q udica 

and what kind of container are you running? 

Thanks,
Lukas.

**Comment by wrabcak** [comment]
Hi @rhatdan, 
Did containers team changed the structure of json file in container inspection? It looks so..

**Comment by s4s0l** [comment]
```
rpm -q udica
package udica is not installed
```
... as i said I'm following steps from README.md in this repo. Installation instructions are to get udica from git. My version is from commit 9eec5d82ec4b1be3a63822394235cf1abe2c88b3.

```
podman version
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```
attachment contains container inspection result.
[file.txt](https://github.com/containers/udica/files/3379401/file.txt).

Let me know if u need anything more.

**Comment by wrabcak** [comment]
Hi @s4s0l , 

Could you please try udica from this repository? 
https://github.com/wrabcak/udica/tree/fb-new-podman

Thanks,
Lukas.

**Comment by s4s0l** [comment]
It wokrs.

**Comment by wrabcak** [comment]
Thanks for testing!

**Comment by rhatdan** [comment]
@wrabcak Not conciously...

**Comment by AkihiroSuda** [comment]
seems not fixed: https://github.com/containers/udica/issues/43
