### ISSUE TITLE
Pip installs templates in wrong place

### ISSUE THREAD

**Issue by gatoniel** [containers/udica#59]
**Describe the bug**
`pip install udica` puts the *data_files* (/usr/share/udica/templates/*.cil) in the wrong place. `pip install git+https://github.com/containers/udica` works fine.

**To Reproduce**
1. `pip install udica` then `pip uninstall udica` gives these file listing:

> Uninstalling udica-0.2.1:
>   /usr/local/bin/udica
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/INSTALLER
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/LICENSE
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/METADATA
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/RECORD
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/WHEEL
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/entry_points.txt
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1.dist-info/top_level.txt
>   /usr/local/lib/python3.6/site-packages/udica/__init__.py
>   /usr/local/lib/python3.6/site-packages/udica/__main__.py
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/__init__.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/__main__.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/parse.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/perms.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/policy.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/parse.py
>   /usr/local/lib/python3.6/site-packages/udica/perms.py
>   /usr/local/lib/python3.6/site-packages/udica/policy.py
>   /usr/local/lib/python3.6/site-packages/usr/share/licenses/udica/LICENSE
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/ansible/deploy-module.yml
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/base_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/config_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/home_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/log_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/net_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/tmp_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/tty_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/virt_container.cil
>   /usr/local/lib/python3.6/site-packages/usr/share/udica/templates/x_container.cil
> Proceed (y/n)? y
>   Successfully uninstalled udica-0.2.1

2. `pip install git+https://github.com/containers/udica` and then `pip uninstall udica` gives the correct listing:

> Uninstalling udica-0.2.1:
>   /usr/local/bin/udica
>   /usr/local/lib/python3.6/site-packages/udica-0.2.1-py3.6.egg-info
>   /usr/local/lib/python3.6/site-packages/udica/__init__.py
>   /usr/local/lib/python3.6/site-packages/udica/__main__.py
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/__init__.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/__main__.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/parse.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/perms.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/__pycache__/policy.cpython-36.pyc
>   /usr/local/lib/python3.6/site-packages/udica/parse.py
>   /usr/local/lib/python3.6/site-packages/udica/perms.py
>   /usr/local/lib/python3.6/site-packages/udica/policy.py
>   /usr/share/licenses/udica/LICENSE
>   /usr/share/udica/ansible/deploy-module.yml
>   /usr/share/udica/templates/base_container.cil
>   /usr/share/udica/templates/config_container.cil
>   /usr/share/udica/templates/home_container.cil
>   /usr/share/udica/templates/log_container.cil
>   /usr/share/udica/templates/net_container.cil
>   /usr/share/udica/templates/tmp_container.cil
>   /usr/share/udica/templates/tty_container.cil
>   /usr/share/udica/templates/virt_container.cil
>   /usr/share/udica/templates/x_container.cil
> Proceed (y/n)? y
>   Successfully uninstalled udica-0.2.1

**Expected behavior**
`pip install udica` should show the same behaviour as `pip install git+https://github.com/containers/udica` 

**Additional context**
-

**Comment by wrabcak** [comment]
Hi @gatoniel , 
Thank you for issue report. 

What is the version of pip and what distribution are you using? 

On my Fedora-32, it works as expected:
```
# pip install udica 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting udica
  Using cached https://files.pythonhosted.org/packages/f8/a2/fc4acc53ea6efce2f3b85720d8de36ce834faf12289ccefb54d8ad9117cb/udica-0.2.1.tar.gz
Installing collected packages: udica
    Running setup.py install for udica ... done
Successfully installed udica-0.2.1

# ls /usr/share/udica/templates/
base_container.cil    home_container.cil  net_container.cil  tty_container.cil   x_container.cil
config_container.cil  log_container.cil   tmp_container.cil  virt_container.cil
```

**Comment by gatoniel** [comment]
Hi,

I am on CentOS 8 and was using an old pip version (9.0.3), so I updated to 20.1.1 (pip 20.1.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)). When I use `pip install udica --no-cache-dir` it works fine. But using `pip install udica` puts the templates in the wrong place... Maybe this is more of a pip problem or there is just one bad package in my cache.

**Comment by wrabcak** [comment]
Hi @gatoniel, 
For me it works as expected also on RHEL-8. 
```
# rpm -q python3-pip
python3-pip-9.0.3-16.el8.noarch

# # ls /usr/share/udica/templates/
base_container.cil    home_container.cil  net_container.cil  tty_container.cil   x_container.cil
config_container.cil  log_container.cil   tmp_container.cil  virt_container.cil
```
I don't see any issue in setup files. I'll close this ticket, if you find some reproducer, I'm happy to help.
