### ISSUE TITLE
parse error when try to create my_container profile from container.json

### ISSUE THREAD

**Issue by HariAccuknox** [containers/udica#72]
**Describe the bug**
When try to parse container.json to udica policy my_container, throws parsing error . The parser.py items() cannot parse the port 
list in container.json

![Screenshot from 2020-09-13 19-54-38](https://user-images.githubusercontent.com/66108054/93031907-f87ad100-f64b-11ea-9fdd-5f6c9366649a.png)

**Additional context**
PS: i ran the container without the port number, still error in parsing attributes

**Comment by wrabcak** [comment]
Hi, 
Can you please share the container.json file and version of the udica? 

Thanks,
Lukas.

**Comment by svc2497** [comment]
[container.zip](https://github.com/containers/udica/files/5217805/container.zip)

udica in /usr/local/lib/python3.8/site-packages (0.2.2)

**Comment by svc2497** [comment]
Thanks for your swift response

regards
Hari

**Comment by wrabcak** [comment]
Thanks, what about version of podman/docker container engine?

**Comment by svc2497** [comment]
![Screenshot from 2020-09-14 17-50-38](https://user-images.githubusercontent.com/69899749/93085203-d7010000-f6b2-11ea-9bc1-1c0ed21b1556.png)

**Comment by wrabcak** [comment]
Please update podman package to the latest stable version which is 2.0+ .

**Comment by svc2497** [comment]
![Screenshot from 2020-09-14 22-01-45](https://user-images.githubusercontent.com/69899749/93112827-10973280-f6d6-11ea-8771-7da64a366226.png)
 @wrabcak  it is working perfectly. Thank you so much for the effort

**Comment by wrabcak** [comment]
Based on previous comment closing this ticket.
