### ISSUE TITLE
SQL Client cannot connect to instance in web

### ISSUE THREAD

**Issue by Davidnet** [containers/udica#81]
**Describe the bug**
I have a php application that I develop that I run sans problems with the following:

```bash
podman run --privileged --rm -v (pwd)/einvoices/:/var/www/html/apidian2020/storage/app/public/:Z -p 9000:80 api-facturacion:production
```
Since I want to try udica I decided to start:
```bash
podman run --rm -v (pwd)/einvoices/:/var/www/html/apidian2020/storage/app/public/:rw -p 9000:80 api-facturacion:production
``` 

This created the following policy:

```bash
(block rocky-einvoice
    (blockinherit container)
    (blockinherit restricted_net_container)
    (allow process process ( capability ( audit_write chown dac_override fowner fsetid kill net_bind_service setfcap setgid setpcap setuid sys_chroot )))

    (allow process mysqld_port_t ( tcp_socket (  name_bind )))
    (allow process http_port_t ( tcp_socket (  name_bind )))
    (allow process user_home_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
    (allow process user_home_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
    (allow process user_home_t ( sock_file ( append getattr open read write )))
)
```
I installed in selinux:

```bash
sudo semodule -i rocky-einvoice.cil /usr/share/udica/templates/{base_container.cil,net_container.cil}
``` 
and run:
```bash
podman run --security-opt label=type:rocky-einvoice.process --rm -v (pwd)/einvoices/:/var/www/html/apidian2020/storage/app/public/:rw -p 9000:80 api-facturacion:production
```
and mysql migration dies, what can I see from journalctl is this:

```bash
AVC avc:  denied  { name_connect } for  pid=883848 comm="php" dest=3306 scontext=system_u:system_r:rocky-einvoice.process:s0:c116,c642 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket permissive=0
```

Any help? Thanks!

**To Reproduce**
Create an instance in any cloud platform and run:

```bash
podman run --security-opt label=type:rocky-einvoice.process -it --rm --net host mysql mysql -vvv -h$(host) -uroot -p
```
Result:
```bash
ERROR 2003 (HY000): Can't connect to MySQL server on 'redactedhost' (13)
```

rocky-einvoice is the policy generated by udica

logs:
```bash
AVC avc:  denied  { name_connect } for  pid=916447 comm="mysql" dest=3306 scontext=system_u:system_r:rocky-einvoice.process:s0:c263,c861 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket permissive=0
```

**Expected behavior**:

Being able to connect to SQL instance externally

**Additional context**
Any resources to learn about more udica? Thanks! Amazing product!

**Comment by Davidnet** [comment]
I have added name_connect to: allow process mysqld_port_t ( tcp_socket name_connect) 

But I do not know if this is a correct way to solve it.

If you can point me in the right direction I will appreciate it.

**Comment by wrabcak** [comment]
Hello @Davidnet , 

Adding allow rule as you defined:
`allow process mysqld_port_t ( tcp_socket (name_connect)))`

Is the best approach you can do. The problem here is that udica cannot know that software inside the container will connect to any port. There is no way how to detect it. 

There are two ways how to deal with such situation in future: 
- use parameter `--append-rules` where you can provide file with SELinux denials and udica will re-generate the policy and append rules for denials from the file. 
-  use `--full-network-access` to allow all network access to the container. 

I hope this helps. 
Thanks,
Lukas.
