### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rhatdan** [containers/udica#89]

**Comment by cevich** [comment]
***Supporting/Required changes:***

- [ ] Update `$DEST_BRANCH` in `.cirrus.yml` ***and*** default value in `./contrib/cirrus/lib.sh` and `contrib/cirrus/pr-should-include-tests`
- [ ] Update value in `contrib/cirrus/build.sh` for `[[ "$PODMAN_FROM" == 'master' ]]`

(I'll update this comment as/if I find more)

**Comment by vmojzis** [comment]
> _**Supporting/Required changes:**_
> 
> * [ ]  Update `$DEST_BRANCH` in `.cirrus.yml`
> * [ ]  Update value in `contrib/cirrus/build.sh` for `[[ "$PODMAN_FROM" == 'master' ]]`
> 
> (I'll update this comment as/if I find more)

@cevich  Thanks for the info.
Do we really want to edit the "$PODMAN_FROM" value in "contrib/cirrus/build.sh"? 
Podman still seems to be on "master" - https://github.com/containers/podman/issues/10329

**Comment by vmojzis** [comment]
> _**Supporting/Required changes:**_
> 
> * [ ]  Update `$DEST_BRANCH` in `.cirrus.yml`
> * [ ]  Update value in `contrib/cirrus/build.sh` for `[[ "$PODMAN_FROM" == 'master' ]]`
> 
> (I'll update this comment as/if I find more)

@cevich Thanks for the info.
What do you mean by the second bullet point? I could allow for both 'master' and 'main' for now, but I don't see a point in that until we also update "$PODMAN_FROM" in ".cirrus.yml"

**Comment by rhatdan** [comment]
The branch has been renamed.
