### ISSUE TITLE
--append-rules does not work (or I am doing it wrong)

### ISSUE THREAD

**Issue by laolux** [containers/udica#96]
**Describe the bug**
Using `--append-rules` does not change the resulting `.cil` file.

**To Reproduce**
1. Generate a custom policy for a container using `udica -j alpine-ssh.json alpine-ssh`.
2. Load the custom policy using `semodule -i alpine-ssh.cil /usr/share/udica/templates/base_container.cil`
3. Start the container again, this time using the `--security-opt label=type:alpine-ssh.process` parameter
4. Get avc denial message and dump into file: `ausearch -m AVC,USER_AVC -ts recent > avcfile`
5. Generate new custom policy using `udica -j alpine-ssh.json --append-rules avcfile alpine-ssh2`
6. Load the new policy and run the container with the new policy.

**Expected behavior**
Container runs with new policy without generating AVC messages.

**What really happens**
Newly generated policy `alpine-ssh2.cil` is identical to the old one `alpine-ssh.cil` (the one without the `--append-rules`).
Loading the new policy does not make any difference and the container still fails, generating AVC messages.

**Additional context**
The container is a very basic alpine container which has openssh-client installed.
Container created using buildah:

    ctr=$(buildah from docker.io/library/alpine:3)
    buildah run $ctr -- apk update
    buildah run $ctr -- apk add openssh-server openssh-client openssh-sftp-server
    buildah commit $ctr alpine-ssh

AVC denials appear when the container tries to establish a new ssh connection to the outside.
Container is run without capabilities as non-root user (works fine when not using udica):
`podman run --cap-drop=all -it 2259a108709b /bin/sh`
`.cil' file generated by udica:

    (block alpine-ssh
        (blockinherit container)
    )

`avcfile` generated using `ausearch -m AVC,USER_AVC -ts recent > avcfile` and looks similar to the one in `tests/append_avc_file`:

    time->Mon Jul  5 11:50:12 2021
    type=AVC msg=audit(1625453412.556:1282): avc:  denied  { name_connect } for  pid=5543 comm="ssh" dest=22 scontext=system_u:system_r:alpine-ssh.process:s0:c7,c136 tcontext=system_u:object_r:ssh_port_t:s0 tclass=tcp_socket permissive=0

**Comment by vmojzis** [comment]
When trying your reproducer, I get the following warning:
`WARNING: process type: alpine-ssh.process seems to be unrelated to this container policy. Skipping allow rule.`

Which is due to the name change of your new .cil file.
Please try using "alpine-ssh" (instead of "alpine-ssh2") as the container name in step 5:
`udica -j alpine-ssh.json --append-rules avcfile alpine-ssh`

**Comment by laolux** [comment]
Thanks, that solves it. So I was doing it wrong.
I thought that when I use both `-j` and `--append-rules`, then udica would create a new policy from the info given in `-j` and at the same time append with the stuff given by `--append-rules`.
Thanks again and sorry for the noise.

**Comment by vmojzis** [comment]
> Thanks, that solves it. So I was doing it wrong.
> I thought that when I use both `-j` and `--append-rules`, then udica would create a new policy from the info given in `-j` and at the same time append with the stuff given by `--append-rules`.
> Thanks again and sorry for the noise.

It does, but _udica_ also checks the source context of given AVCs against the container name you provide, to make sure you are only adding relevant policy rules (to avoid influencing other container policies).
The source context of the AVC is "system_u:system_r:**alpine-ssh**.process:s0:c7,c136", so udica will only add this rule to a policy for container named **alpine-ssh**

**Comment by laolux** [comment]
> It does, but _udica_ also checks the source context of given AVCs against the container name you provide, to make sure you are only adding relevant policy rules (to avoid influencing other container policies).

Oh, that's incredibly convenient! So I can pretty much just dump the AVC output to udica and do not need to manually remove the irrelevant messages of other containers/system issues. That's really great!
